### ISSUE TITLE
dist folder not included in NPM package

### ISSUE THREAD

**Issue by hammadj** [Kiikurage/babel-plugin-flow-to-typescript#22]
Followed the instructions exactly in the Readme, got this error:

![image](https://user-images.githubusercontent.com/7143583/49763972-67fba980-fc8b-11e8-9d46-772f3979f4e0.png)

Checked in the `node_modules/babel-plugin-flow-to-typescript` folder and there's nothing but this:
![image](https://user-images.githubusercontent.com/7143583/49763996-7f3a9700-fc8b-11e8-9fc1-28e03a4064d5.png)

**Comment by antonycourtney** [comment]
Hitting the same issue. Is there a workaround?

**Comment by Kiikurage** [comment]
@hammadj @antonycourtney Hmm. Currently we have no workaround about it. I'll investigate more in this weekend.

**Comment by antonycourtney** [comment]
@Kiikurage Thanks for looking into it.  For what it's worth I managed to work around by cloning the repository, building locally, and then copying the `dist` dir from local build into the `node_modules/babel-plugin-flow-to-typescript` directory in the project I wanted to convert. I imagine doing an npm install from my local build (instead of from npm) would also have worked.
Overall just looks like a bad publish on npm that inadvertently omitted the build dir.

**Comment by haggholm** [comment]
@Kiikurage You’ve added `dist` to your `.gitignore`, which seems appropriate. But you have no `.npmignore`…and with no `.npmignore`, npm defaults to using `.gitignore`.

Creating an appropriate `.npmignore` should fix it.

**Comment by steelbrain** [comment]
Here's a patch for it if someone wants to do a PR https://github.com/steelbrain/babel-plugin-flow-to-typescript/commit/9ce943e71509da4d103b2416576e2c078019771f

**Comment by swansontec** [comment]
Another solution is to put a `files` whitelist in the package.json file. This is generally more maintainable than the `.npmignore` blacklist. Let me get a PR ready.

**Comment by nihaux** [comment]
plop any news on this ?
